<<<<<<< HEAD
# https://devcenter.heroku.com/articles/java-support#specifying-a-java-version
java.runtime.version=17
=======
# https://devcenter.heroku.com/articles/java-support#specifying-a-java-version
java.runtime.version=17
>>>>>>> 9507a180c83b698c6e2aece99517229bd06ccd10
